### ISSUE TITLE
[static] Static.Serve should allow custom headers

### ISSUE THREAD

**Issue by notzippy** [revel/modules#45]
## TODO
- [x] move this issue to the `revel/modules/static` module
- [ ] add config option for static file caching
- [ ] add cache header code to `static` module
See revel/revel#352
